### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by sjiaofasdad** [amprocode/Bloxflip-rain-notifier#13]
<title>Attention Required! | Cloudflare</title>
Every time i try run it with cmd

**Comment by sjiaofasdad** [comment]
And Expecting value: line 1 column 1 (char 0)

**Comment by sjiaofasdad** [comment]
Expecting value: line 1 column 1 (char 0)???!

**Comment by amprocode** [comment]
this was due to a bloxflip update that has since been reverted, it should be working fine now
