### ISSUE TITLE
chrome instant closing

### ISSUE THREAD

**Issue by yulus420** [amprocode/Bloxflip-rain-notifier#3]
chrome is instanly closing and main.exe is giving error:
Traceback (most recent call last):
  File "main.py", line 42, in <module>
  File "selenium\webdriver\chrome\webdriver.py", line 70, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 93, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 269, in __init__
  File "selenium\webdriver\remote\webdriver.py", line 360, in start_session
  File "selenium\webdriver\remote\webdriver.py", line 425, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 247, in check_response
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 101
Current browser version is 100.0.4896.127 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
        Ordinal0 [0x00C2B8F3+2406643]
        Ordinal0 [0x00BBAF31+1945393]
        Ordinal0 [0x00AAC748+837448]
        Ordinal0 [0x00ACC8B3+968883]
        Ordinal0 [0x00AC84BA+951482]
        Ordinal0 [0x00AC5D71+941425]
        Ordinal0 [0x00AF8EE0+1150688]
        Ordinal0 [0x00AF8B3A+1149754]
        Ordinal0 [0x00AF4096+1130646]
        Ordinal0 [0x00ACE636+976438]
        Ordinal0 [0x00ACF546+980294]
        GetHandleVerifier [0x00E99612+2498066]
        GetHandleVerifier [0x00E8C920+2445600]
        GetHandleVerifier [0x00CC4F2A+579370]
        GetHandleVerifier [0x00CC3D36+574774]
        Ordinal0 [0x00BC1C0B+1973259]
        Ordinal0 [0x00BC6688+1992328]
        Ordinal0 [0x00BC6775+1992565]
        Ordinal0 [0x00BCF8D1+2029777]
        BaseThreadInitThunk [0x76DBFA29+25]
        RtlGetAppContainerNamedObjectPath [0x773B7A7E+286]
        RtlGetAppContainerNamedObjectPath [0x773B7A4E+238]

[88

**Comment by amprocode** [comment]
On your chrome browser go to: chrome://settings/help and check your chrome version (if it needs updating make sure you update it).
Then head to https://chromedriver.chromium.org/downloads and download the chromedriver version that corresponds with your current chrome version and download the **chromedriver_win32.zip** file.
Now extract the chromedriver folder and you should be left with a chromedriver.exe file. Copy and paste this file into the folder where your main.exe is located.
run main.exe and update here if it works or doesnt work

**Comment by yulus420** [comment]
i think its working im waiting for rain now everything is good but when i open main.exe it says
Expecting value: line 1 column 1 (char 0)

**Comment by amprocode** [comment]
Thanks for letting me know about this issue! This should now be fixed in v1.3.3
