### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by jayjayasap** [amprocode/Bloxflip-rain-notifier#7]
When you open it is it supposed to close immediatly right after? Or is that normal?

**Comment by amprocode** [comment]
the program should stay open...
you getting any errors?

**Comment by jayjayasap** [comment]
Well i've gotten that to work, but now it is saying "Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?" everytime i run either installer.bat or main.py. Do you have any idea on what this means?

**Comment by amprocode** [comment]
pip install lxml
that should do the trick! Will update installer.bat now

**Comment by jayjayasap** [comment]
Alright, thanks
