### ISSUE TITLE
shit

### ISSUE THREAD

**Issue by TurfuFrogy** [amprocode/Bloxflip-rain-notifier#8]
Shitty method to detect rains, trash code. Have a nice day!

**Comment by amprocode** [comment]
Just out of curiosity, how would you detect rains?

**Comment by TurfuFrogy** [comment]
Using their websocket.

**Comment by TurfuFrogy** [comment]
Yes you need to bypass cloudflare

**Comment by amprocode** [comment]
just done some tinkering and found this is possible. thanks for your help! i will be updating this soon
