### ISSUE TITLE
EXE version works, but py doesnt

### ISSUE THREAD

**Issue by Catch-c** [amprocode/Bloxflip-rain-notifier#9]
Hey,

So when I use the exe version it works, but the open source py one doesnt. The py one just closes instantly with no errors. I want to use the opensource one so I can customise the message.

**Comment by Catch-c** [comment]
![image](https://user-images.githubusercontent.com/80603287/175179653-5d2e1c17-9aa5-4acf-acba-e66b5ebbd86b.png)
nvm it does give an error above

**Comment by amprocode** [comment]
run the installer or do **pip install requests**

**Comment by Catch-c** [comment]
says its already installed, and same error/closing instantly.

**Comment by amprocode** [comment]
Thats odd.
- Try reinstalling python
- Try reinstalling requests package (**pip uninstall requests** then **pip install requests**)
- Use exe version

I will be releasing an updated version soon anyway.
Let me know if you fix it and if you can i have a server where this is hosted 24/7
